eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://114.115.208.105:8888/eureka/
server:
  port: 8084
spring:
  application:
    name: service-menu
    host: 114.115.208.105