eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.136:8888/eureka/
  instance:
#      ip-address: 114.115.208.105
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
      preferIpAddress: true
#      instance-id: http://114.115.208.105:${server.port}
server:
  port: 8084
spring:
  application:
    name: service-menu
