eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.136:8888/eureka/
  instance:
      ip-address: 192.168.1.136
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
      preferIpAddress: true
      instance-id: http://192.168.1.136:${server.port}
server:
  port: 8084
spring:
  application:
    name: service-menu
