server:
  port: 8888 # 注册中心占用8080端口
eureka:
  instance:
    hostname: 114.115.208.105
    ip-address: 114.115.208.105
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:8888/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 172.17
