server:
  port: 8888 # 注册中心占用8080端口
eureka:
  instance:
    hostname: 172.21.0.9
    ip-address: 172.21.0.9
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:8888/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
# spring:
#  cloud:
 #   inetutils:
 #     preferredNetworks:
  #      - 172.17
