server:
  port: 8888 # 注册中心占用8080端口
eureka:
  instance:
    hostname: 114.115.208.105
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:8888/eureka/