eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://114.115.208.105:8888/eureka/
  instance:
#      ip-address: 114.115.208.105
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
      preferIpAddress: true
#      instance-id: http://192.168.1.196:${server.port}
server:
  port: 8080
spring:
  application:
    name: service-page
  thymeleaf:
    prefix: classpath:/templates/,classpath:/static/

zuul:
  routes:
    menu0:
      path: /menu/index
      serviceId: SERVICE-MENU
    menu2:
      path: /lhb/index
      serviceId: SERVICE-MENU
    info0:
      path: /ztsj/index
      serviceId: SERVICE-INFO
    info1:
      path: /ztsj/ztgn
      serviceId: SERVICE-INFO
    info2:
      path: /ztsj/fx
      serviceId: SERVICE-INFO
    info3:
      path: /ztsj/save
      serviceId: SERVICE-INFO
    info4:
      path: /ztsj/delete
      serviceId: SERVICE-INFO
    info5:
      path: /spmm/index
      serviceId: SERVICE-INFO
    info6:
      path: /spmm/luoji
      serviceId: SERVICE-INFO
    info7:
      path: /spmm/stocks
      serviceId: SERVICE-INFO
    info8:
      path: /spmm/save
      serviceId: SERVICE-INFO
    info9:
      path: /spmm/delete
      serviceId: SERVICE-INFO
    info10:
      path: /spmm/fx
      serviceId: SERVICE-INFO
    info11:
      path: /spmm/delete
      serviceId: SERVICE-INFO
    info12:
      path: /gfjgd/index
      serviceId: SERVICE-INFO
    info13:
      path: /gfjgd/fx
      serviceId: SERVICE-INFO
    info14:
      path: /ccgp/index
      serviceId: SERVICE-INFO
    info15:
      path: /ccgp/save
      serviceId: SERVICE-INFO
    info16:
      path: /ccgp/delete
      serviceId: SERVICE-INFO
    info17:
      path: /ccgp/getStock
      serviceId: SERVICE-INFO

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000