eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://114.115.208.105:8888/eureka/
  instance:
      ip-address: 114.115.208.105
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
      preferIpAddress: true
      instance-id: ${spring.cloud.client.ipAddress}:${server.port}
server:
  port: 8080
spring:
  application:
    name: service-page
  thymeleaf:
    prefix: classpath:/templates/,classpath:/static/

#
#zuul:
#  routes:
#    menu1:
#      path: /menu/**
#      serviceId: SERVICE-MENU
#    menu2:
#      path: /thsLhb/**
#      serviceId: SERVICE-MENU
#    info1:
#      path: /ztsj/**
#      serviceId: SERVICE-INFO
#    info2:
#      path: /ztgn/**
#      serviceId: SERVICE-INFO
#    info3:
#      path: /spmm/**
#      serviceId: SERVICE-INFO
#    info4:
#      path: /ccgp/**
#      serviceId: SERVICE-INFO
#    info5:
#      path: /gfjgd/**
#      serviceId: SERVICE-INFO
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000