eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://114.115.208.105:8888/eureka/
server:
  port: 8080
spring:
  application:
    name: service-page
  thymeleaf:
    prefix: classpath:/templates/,classpath:/static/