eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://114.115.208.105:8888/eureka/
  instance:
      ip-address: 114.115.208.105
      lease-expiration-duration-in-seconds: 30
      lease-renewal-interval-in-seconds: 10
      preferIpAddress: true
#      instance-id: http://192.168.1.196:${server.port}
server:
  port: 8080
spring:
  application:
    name: service-page
  thymeleaf:
    prefix: classpath:/templates/,classpath:/static/

zuul:
  routes:
    menu0:
      path: /menu/**
      serviceId: SERVICE-MENU
    menu2:
      path: /lhb/**
      serviceId: SERVICE-MENU
    info0:
      path: /ztsj/**
      serviceId: SERVICE-INFO
    info5:
      path: /spmm/**
      serviceId: SERVICE-INFO
    info12:
      path: /gfjgd/**
      serviceId: SERVICE-INFO
    info14:
      path: /ccgp/**
      serviceId: SERVICE-INFO

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000